apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    app: "{{ cluster_name }}"
    cloud: Amazon
    name: "{{ cluster_name }}"
    vendor: OpenShift
    safe-destroy: 'false'
    purpose: 'managed-cluster'
    type: managed
    region: "{{ cluster_region }}"
    env: "{{ ocp_cluster.env }}"
  name: "{{ cluster_name }}"
spec:
  hubAcceptsClient: true
