---
- name: Add AWS Managed Policy to Worker Nodes
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Add AWS Policy to Node
      include_role:
        name: add_aws_node_policy