---
- name: Install Cluster Certificates
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - install_certificates
  collections:
    - aws.awscollections
  tasks:
    - debug:
        msg: "Install Cluster Certificates"

    - name: Install certificates to AWS
      include_role:
        name: install_certs_aws
      vars:
        cluster_name: '{{ ocp_cluster.name }}'

