kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
subjects:
  # This user is for kubeadmin via CLI
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'kube:admin'
  # This user is for ansible automation
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
