---
- name: Configure Loki
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - configure loki
  vars:
    manifests_output_path: "../../ocp-gitops-infra-config/clusters/{{ cluster_name }}"
    output_path: "{{ manifests_output_path }}/loki"
  tasks:
    - debug:
        msg: "configure loki"
    - name: Configure Loki
      include_role:
        name: configure_loki

