---
#################################################################################
############ Deploy Hub Cluster
#################################################################################
- name: Prepare for hub cluster install
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "~/.{{ cloud_provider }}/ is present"
      file:
        path: "~/.{{ cloud_provider }}/"
        state: directory

    - name: "Set {{ cloud_provider }}_creds fact"
      set_fact:
        cloud_creds: "{{ lookup('file', './cloud_providers/{{ cloud_provider }}/files/{{ cloud_provider }}_creds') }}"
      no_log: true

    - name: Copy credentials
      template:
        src: "./templates/credentials.j2"
        dest: "~/.{{ cloud_provider }}/credentials"
      no_log: true

- import_playbook: "./cloud_providers/{{ cloud_provider }}/deploy_hub_cluster.yaml"
  tags:
    - deploy_hub_cluster

- name: Manage kubeconfig and credentials
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set kubeconfig fact
      set_fact:
        kubeconfig: "{{ working_dir }}/install/{{ hub_cluster_name }}/auth/kubeconfig"

    - name: Set cluster_name
      set_fact:
        cluster_name: "{{ hub_cluster_name }}"

    - name: Set hub fact
      set_fact:
        cluster_type: 'hub'

    - name: Store kubeadmin creds
      include_role:
        name: store_kubeadmin_pass

- import_playbook: "./install-rhacm.yaml"
  tags:
    - install_rhacm

- import_playbook: "./setup-sso.yaml"
  tags:
    - setup_sso

################################################################################
########### Post Cluster Deploy Tasks
################################################################################

- import_playbook: "./cloud_providers/{{ cloud_provider }}/post_cluster.yaml"
  tags:
    - post_cluster
    - post_cluster_tasks
  vars:
    cloud_provider: '{{ ocp_cluster.platform }}'
