---
- name: Store kubeadmin-password in encrypted file
  gather_facts: false
  hosts: localhost
  vars_prompt:
    - name: kubeadmin_pass
      prompt: Enter Kubeadmin Password
      private: yes
      confirm: yes
  tasks:
    - name: Set infra-config output path
      set_fact:
        infra_out_clusters: "../../ocp-gitops-infra-config/clusters"

    - name: Encrypt file
      command: ansible-vault encrypt_string --vault-password-file ~/.passfile '{{ kubeadmin_pass }}' --name 'kubeadmin_pass'
      register: encrypted_var

    - name: Create cluster auth output dir
      ansible.builtin.file:
        state: directory
        path: "{{ infra_out_clusters }}/{{ cluster_name }}/auth"
      register: manifests_output_dir

    - name: Create kubeadmin-password file
      copy:
        dest: "{{ infra_out_clusters }}/{{ cluster_name }}/auth/kubeadmin-password"
        content: "{{ encrypted_var.stdout }}"