---
#################################################################################
############ Install Certificates
#################################################################################
- name: Prepare for certificate install
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "~/.{{ cloud_provider }}/ is present"
      file:
        path: "~/.{{ cloud_provider }}/"
        state: directory

    - name: "Set {{ cloud_provider }}_creds fact"
      set_fact:
        cloud_creds: "{{ lookup('file', './cloud_providers/{{ cloud_provider }}/files/{{ cloud_provider }}_creds') }}"
      no_log: true

    - name: Copy credentials
      template:
        src: "./templates/credentials.j2"
        dest: "~/.{{ cloud_provider }}/credentials"
      no_log: true

- import_playbook: "./cloud_providers/{{ cloud_provider }}/install_certificates.yaml"
  tags:
    - install_certificates